# Generated by Django 3.1.6 on 2021-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('methods', models.TextField(max_length=160)),
                ('photo_link', models.URLField()),
            ],
        ),
    ]
