# Generated by Django 3.1.6 on 2021-02-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_rawdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='created_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='therapist',
            name='photo_id',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='therapist',
            name='therapist_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='methods',
            field=models.TextField(max_length=300),
        ),
    ]
